---
title: "Week 2: Basics of R Programming"
output: html_notebook
---




#R Objects

```{r}
a = 1 #OR
a <- 1

a

a+2


```


```{r}
#case-sensitive

Name = 1
name = 0

Name + 1


```


```{r}
#R will overwrite any previous information stored in an object without asking

my_number <-  1 
my_number ## 1 
my_number <-  999 
my_number ## 999
```

```{r}
#You can see which object names you have already used with the function ls:
ls()
```


#Vectors

```{r}
#Vectors are different from objects as they keep more than one value.
die <-  1:6 #a vector.
die #keeps numbers between 1 and 6.

#You now have a virtual die that is stored in your computer’s memory. You can access it whenever you like by typing the word die
```


```{r calculations}
#R does not always follow the rules of matrix multiplication. Instead, R uses element-wise execution. 
#When you are making calculations, R will apply the same operation to each element in the set. 
#So for example, when you run die - 1, R subtracts 1 from each element of die.

die - 1 ## 0 1 2 3 4 5 
die / 2 ## 0.5 1.0 1.5 2.0 2.5 3.0 
die * die ## 1 4 9 16 25 36

```



```{r unequal objects}
#If you give R two vectors of unequal lengths, R will repeat the shorter vector until it is as long as the longer vector, and then do the math.

die       ## 1 2 3 4 5 6 
die + 1:2 ## 2 4 4 6 6 8 
die + 1:4 ## 2 4 6 8 6 8

#Warning in die + 1:4 : longer object length is not a multiple of shorter object length


```



#Functions

```{r}
#R comes with many functions that you can use to do sophisticated tasks.

round(3.1415) ## 3 
factorial(3) ## 6

```


```{r}
#The data that you pass into the function is called the function’s argument.

mean(1:6) ## 3.5 
mean(die) ## 3.5 

round(mean(die)) ## 4
#R works from the inside out.
#You can feed a function with another function.

```

```{r}
#Those were actually the default modes of the functions.
#But how can I know this?
##How can I know the default mode of any function?

args(round) #function (x, digits = 0, ...) 

round(3.1415) ## 3
round(3.1415, digits = 2) ## 3.14
```


```{r}
#If you try to use a name that a function does not expect, you will likely get an error: 
round(3.1415, corners = 2) ## Error in round(3.1415, corners = 2) : unused argument(s) (corners = 2)
```


##Sampling without replacement

```{r}
#By default, sample builds a sample without replacement.
args(sample)

#If I randomly choose 2 values (size) by turns, from the die vector, which values I am likely to get?
sample(die, size = 2) #2 1

#As you can see results are changing each time we run the codes as we are picking the values "randomly".
```


```{r}
#You can simulate a roll of the die with R’s sample function. 
##To roll your die and get a number back, set x to die and sample one element from it. 

sample(x = die, size = 1) ##
sample(x = die, size = 1) ##  
sample(x = die, size = 1) ## 

sample(x = die, size = 2) ## 
sample(x = die, size = 2) ##
sample(x = die, size = 2) ##
```


##Sampling with replacement


```{r}
#You can recreate this behavior in sample by adding the argument replace = TRUE: 
sample(die, size = 2, replace = TRUE) ## 5 5
```

```{r}
#If you want to add up the dice, you can feed your result straight into the sum function.
##You can store of the results of the sample function using " <- " operator.

dice <- sample(die, size = 2, replace = TRUE) 
dice ## 
sum(dice) ## 
```

```{r}
#What would happen if you call dice multiple times? Would R generate a new pair of dice values each time?

dice #

dice #

dice #

#dice stores the results of the sample function, not the way it behaves.

#R won’t rerun sample(die, 2, replace = TRUE) to create a new roll of the dice

#However, it would be convenient to have an object that can re-roll the dice whenever you call it. 
#You can make such an object by writing your own R function.
```









